name: CI
on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request: {}

jobs:
  # TODO: drop it when GitHub supports its by itself
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint the code with Clippy
        run: cargo clippy -- -Dwarnings

      - name: Run the test suite
        run: cargo test

      - name: Run benchmarks
        run: cargo bench --verbose

  ci-pass:
    name: 'ci-pass'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Merge into master"
        run: exit 0